/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\factory\scene.gltf -t -r public 
Author: amandhiman46 (https://sketchfab.com/amandhiman46)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/factory-4b62e51b1cb94094ae631d634a6e6530
Title: Factory
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    pCube16polySurface73_project_initialShadingGroup2_0: THREE.Mesh;
    objWaterFi_project_lambert2SG1_0: THREE.Mesh;
    objWaterFi1_project_lambert2SG1_0: THREE.Mesh;
    objWaterFi2_project_lambert2SG1_0: THREE.Mesh;
    pCube24_project_initialShadingGroup2_0: THREE.Mesh;
    Cylinder31_project_lambert5SG1_0: THREE.Mesh;
    polySurface22_project_lambert4SG1_0: THREE.Mesh;
    polySurface25_project_lambert4SG1_0: THREE.Mesh;
    polySurface26_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface26_project_lambert5SG1_0: THREE.Mesh;
    Tube003_project_initialShadingGroup2_0: THREE.Mesh;
    Cylinde292_project_initialShadingGroup2_0: THREE.Mesh;
    pCube26_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface27_project_lambert4SG1_0: THREE.Mesh;
    Cylinder33_project_lambert5SG1_0: THREE.Mesh;
    Cylinder33_project_initialShadingGroup2_0: THREE.Mesh;
    Cylinder33_project_initialShadingGroup2_0_1: THREE.Mesh;
    Cylinde293_project_initialShadingGroup2_0: THREE.Mesh;
    Tube004_project_initialShadingGroup2_0: THREE.Mesh;
    Tube005_project_initialShadingGroup2_0: THREE.Mesh;
    Tube006_project_initialShadingGroup2_0: THREE.Mesh;
    Turbina_N220908_Cylinder20_project_initialShadingGroup2_0: THREE.Mesh;
    Turbina_N220908_Cylinder20_project_initialShadingGroup2_0_1: THREE.Mesh;
    Turbina_N220908_Cylinder20_project_initialShadingGroup2_0_2: THREE.Mesh;
    Turbina_N220908_Cylinder20_project_blinn1SG1_0: THREE.Mesh;
    polySurface36_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface36_project_blinn1SG1_0: THREE.Mesh;
    polySurface18_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface18_project_lambert3SG1_0: THREE.Mesh;
    polySurface18_project_lambert4SG1_0: THREE.Mesh;
    polySurface47_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface47_project_lambert3SG1_0: THREE.Mesh;
    polySurface47_project_lambert4SG1_0: THREE.Mesh;
    polySurface48_project_lambert5SG1_0: THREE.Mesh;
    polySurface48_project_lambert6SG1_0: THREE.Mesh;
    polySurface48_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface48_project_blinn1SG1_0: THREE.Mesh;
    polySurface20pCylinder9_project_initialShadingGroup2_0: THREE.Mesh;
    pCylinder9polySurface21_project_initialShadingGroup2_0: THREE.Mesh;
    pCylinder9polySurface23_project_initialShadingGroup2_0: THREE.Mesh;
    pCylinder9polySurface35_project_lambert3SG1_0: THREE.Mesh;
    pCylinder9polySurface45_project_initialShadingGroup2_0: THREE.Mesh;
    pCylinder9polySurface46_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface31polySurface29_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface29polySurface32_project_lambert5SG1_0: THREE.Mesh;
    polySurface29polySurface33_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface29polySurface34_project_lambert5SG1_0: THREE.Mesh;
    polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0_1: THREE.Mesh;
    polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0_2: THREE.Mesh;
    polySurface49polySurface42_project_lambert5SG1_0: THREE.Mesh;
    polySurface42polySurface50_project_lambert6SG1_0: THREE.Mesh;
    polySurface42polySurface51_project_lambert5SG1_0: THREE.Mesh;
    polySurface42polySurface52_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface42polySurface53_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface42polySurface54_project_blinn1SG1_0: THREE.Mesh;
    polySurface42polySurface55_project_initialShadingGroup2_0: THREE.Mesh;
    polySurface42polySurface56_project_initialShadingGroup2_0: THREE.Mesh;
  };
  materials: {
    project_initialShadingGroup2: THREE.MeshStandardMaterial;
    project_lambert2SG1: THREE.MeshStandardMaterial;
    project_lambert5SG1: THREE.MeshStandardMaterial;
    project_lambert4SG1: THREE.MeshStandardMaterial;
    project_blinn1SG1: THREE.MeshStandardMaterial;
    project_lambert3SG1: THREE.MeshStandardMaterial;
    project_lambert6SG1: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[]
};

export function Factory(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/factory/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.133}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={
              nodes.pCube16polySurface73_project_initialShadingGroup2_0.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.objWaterFi_project_lambert2SG1_0.geometry}
            material={materials.project_lambert2SG1}
          />
          <mesh
            geometry={nodes.objWaterFi1_project_lambert2SG1_0.geometry}
            material={materials.project_lambert2SG1}
          />
          <mesh
            geometry={nodes.objWaterFi2_project_lambert2SG1_0.geometry}
            material={materials.project_lambert2SG1}
          />
          <mesh
            geometry={nodes.pCube24_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.Cylinder31_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={nodes.polySurface22_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            geometry={nodes.polySurface25_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            geometry={
              nodes.polySurface26_project_initialShadingGroup2_0.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.polySurface26_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={nodes.Tube003_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.Cylinde292_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.pCube26_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.polySurface27_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            geometry={nodes.Cylinder33_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={nodes.Cylinder33_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.Cylinder33_project_initialShadingGroup2_0_1.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.Cylinde293_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.Tube004_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.Tube005_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.Tube006_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.Turbina_N220908_Cylinder20_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.Turbina_N220908_Cylinder20_project_initialShadingGroup2_0_1
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.Turbina_N220908_Cylinder20_project_initialShadingGroup2_0_2
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.Turbina_N220908_Cylinder20_project_blinn1SG1_0.geometry
            }
            material={materials.project_blinn1SG1}
          />
          <mesh
            geometry={
              nodes.polySurface36_project_initialShadingGroup2_0.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.polySurface36_project_blinn1SG1_0.geometry}
            material={materials.project_blinn1SG1}
          />
          <mesh
            geometry={
              nodes.polySurface18_project_initialShadingGroup2_0.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.polySurface18_project_lambert3SG1_0.geometry}
            material={materials.project_lambert3SG1}
          />
          <mesh
            geometry={nodes.polySurface18_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            geometry={
              nodes.polySurface47_project_initialShadingGroup2_0.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.polySurface47_project_lambert3SG1_0.geometry}
            material={materials.project_lambert3SG1}
          />
          <mesh
            geometry={nodes.polySurface47_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            geometry={nodes.polySurface48_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={nodes.polySurface48_project_lambert6SG1_0.geometry}
            material={materials.project_lambert6SG1}
          />
          <mesh
            geometry={
              nodes.polySurface48_project_initialShadingGroup2_0.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={nodes.polySurface48_project_blinn1SG1_0.geometry}
            material={materials.project_blinn1SG1}
          />
          <mesh
            geometry={
              nodes.polySurface20pCylinder9_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.pCylinder9polySurface21_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.pCylinder9polySurface23_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.pCylinder9polySurface35_project_lambert3SG1_0.geometry
            }
            material={materials.project_lambert3SG1}
          />
          <mesh
            geometry={
              nodes.pCylinder9polySurface45_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.pCylinder9polySurface46_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.polySurface31polySurface29_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.polySurface29polySurface32_project_lambert5SG1_0.geometry
            }
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={
              nodes.polySurface29polySurface33_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.polySurface29polySurface34_project_lambert5SG1_0.geometry
            }
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={
              nodes
                .polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes
                .polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0_1
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes
                .polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0_2
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.polySurface49polySurface42_project_lambert5SG1_0.geometry
            }
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={
              nodes.polySurface42polySurface50_project_lambert6SG1_0.geometry
            }
            material={materials.project_lambert6SG1}
          />
          <mesh
            geometry={
              nodes.polySurface42polySurface51_project_lambert5SG1_0.geometry
            }
            material={materials.project_lambert5SG1}
          />
          <mesh
            geometry={
              nodes.polySurface42polySurface52_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.polySurface42polySurface53_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.polySurface42polySurface54_project_blinn1SG1_0.geometry
            }
            material={materials.project_blinn1SG1}
          />
          <mesh
            geometry={
              nodes.polySurface42polySurface55_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            geometry={
              nodes.polySurface42polySurface56_project_initialShadingGroup2_0
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/factory/scene.gltf");

