/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\arcanum_2\scene.gltf -t -r public 
Author: georgiyhazankin (https://sketchfab.com/georgiyhazankin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arcanum-2-85be7d115e234759a31dd5cd3cd9a37b
Title: Arcanum 2
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube_Material_0: THREE.Mesh;
    Cube001_Material_0: THREE.Mesh;
    Cube002_Material_0: THREE.Mesh;
    Sphere022_Material_0: THREE.Mesh;
    Sc_Conifer_bush_A_2_Sc_Conifer_bush_A_bark_0: THREE.Mesh;
    Sc_Conifer_bush_A_2_Sc_Conifer_bush_A_leaves_0: THREE.Mesh;
    Sc_Conifer_bush_A_2_Sc_Conifer_bush_A_flowers_0: THREE.Mesh;
    Sc_Conifer_bush_A_1_Sc_Conifer_bush_A_bark_0: THREE.Mesh;
    Sc_Conifer_bush_A_1_Sc_Conifer_bush_A_leaves_0: THREE.Mesh;
    Sc_Conifer_bush_A_1_Sc_Conifer_bush_A_flowers_0: THREE.Mesh;
    Sc_Conifer_bush_A_4_Sc_Conifer_bush_A_bark001_0: THREE.Mesh;
    Sc_Conifer_bush_A_4_Sc_Conifer_bush_A_leaves001_0: THREE.Mesh;
    Sc_Conifer_bush_A_4_Sc_Conifer_bush_A_flowers001_0: THREE.Mesh;
    Sc_conifer_03004_Sc_conifer_03_bark001_0: THREE.Mesh;
    Sc_conifer_03004_Sc_conifer_03_bark001_0_1: THREE.Mesh;
    Sc_conifer_03004_Sc_conifer_03_bark001_0_2: THREE.Mesh;
    Sc_conifer_03004_Sc_conifer_03_pines001_0: THREE.Mesh;
    ["B��zierCurve002_Material007_0"]: THREE.Mesh;
    Plane001_Material002_0: THREE.Mesh;
    Sphere004_Material008_0: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    Sc_Conifer_bush_A_bark: THREE.MeshStandardMaterial;
    Sc_Conifer_bush_A_leaves: THREE.MeshStandardMaterial;
    Sc_Conifer_bush_A_flowers: THREE.MeshStandardMaterial;
    ["Sc_Conifer_bush_A_bark.001"]: THREE.MeshStandardMaterial;
    ["Sc_Conifer_bush_A_leaves.001"]: THREE.MeshStandardMaterial;
    ["Sc_Conifer_bush_A_flowers.001"]: THREE.MeshStandardMaterial;
    ["Sc_conifer_03_bark.001"]: THREE.MeshStandardMaterial;
    ["Sc_conifer_03_pines.001"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[];
};

export function Scene(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/arcanum_2/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.042}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[83.816, 149.281, -250.36]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={387.493}
          >
            <group position={[0.601, -1.221, -0.419]} scale={0.258}>
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_2_Sc_Conifer_bush_A_bark_0.geometry
                }
                material={materials.Sc_Conifer_bush_A_bark}
              />
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_2_Sc_Conifer_bush_A_leaves_0.geometry
                }
                material={materials.Sc_Conifer_bush_A_leaves}
              />
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_2_Sc_Conifer_bush_A_flowers_0.geometry
                }
                material={materials.Sc_Conifer_bush_A_flowers}
              />
            </group>
            <group position={[-0.532, 0.169, -0.398]} scale={0.258}>
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_1_Sc_Conifer_bush_A_bark_0.geometry
                }
                material={materials.Sc_Conifer_bush_A_bark}
              />
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_1_Sc_Conifer_bush_A_leaves_0.geometry
                }
                material={materials.Sc_Conifer_bush_A_leaves}
              />
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_1_Sc_Conifer_bush_A_flowers_0.geometry
                }
                material={materials.Sc_Conifer_bush_A_flowers}
              />
            </group>
            <group position={[0.529, 1.456, -0.419]} scale={0.258}>
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_4_Sc_Conifer_bush_A_bark001_0.geometry
                }
                material={materials["Sc_Conifer_bush_A_bark.001"]}
              />
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_4_Sc_Conifer_bush_A_leaves001_0
                    .geometry
                }
                material={materials["Sc_Conifer_bush_A_leaves.001"]}
              />
              <mesh
                geometry={
                  nodes.Sc_Conifer_bush_A_4_Sc_Conifer_bush_A_flowers001_0
                    .geometry
                }
                material={materials["Sc_Conifer_bush_A_flowers.001"]}
              />
            </group>
            <group
              position={[-2.004, -2.415, -0.371]}
              rotation={[0, 0, 1.543]}
              scale={0.258}
            >
              <mesh
                geometry={
                  nodes.Sc_conifer_03004_Sc_conifer_03_bark001_0.geometry
                }
                material={materials["Sc_conifer_03_bark.001"]}
              />
              <mesh
                geometry={
                  nodes.Sc_conifer_03004_Sc_conifer_03_bark001_0_1.geometry
                }
                material={materials["Sc_conifer_03_bark.001"]}
              />
              <mesh
                geometry={
                  nodes.Sc_conifer_03004_Sc_conifer_03_bark001_0_2.geometry
                }
                material={materials["Sc_conifer_03_bark.001"]}
              />
              <mesh
                geometry={
                  nodes.Sc_conifer_03004_Sc_conifer_03_pines001_0.geometry
                }
                material={materials["Sc_conifer_03_pines.001"]}
              />
            </group>
            <mesh
              geometry={nodes.Cube_Material_0.geometry}
              material={materials.Material}
              position={[-0.295, -0.797, -0.238]}
              rotation={[0.4, -0.597, 0.8]}
              scale={0.277}
            />
            <mesh
              geometry={nodes.Cube001_Material_0.geometry}
              material={materials.Material}
              position={[-0.09, -1.154, -0.254]}
              rotation={[1.028, 0.161, 1.687]}
              scale={0.277}
            />
            <mesh
              geometry={nodes.Cube002_Material_0.geometry}
              material={materials.Material}
              position={[-0.333, -0.334, -0.247]}
              rotation={[1.595, -0.224, 0.526]}
              scale={0.277}
            />
            <mesh
              geometry={nodes.Sphere022_Material_0.geometry}
              material={materials.Material}
              position={[-0.274, -0.747, -0.372]}
              scale={0.298}
            />
            <mesh
              geometry={nodes["B��zierCurve002_Material007_0"].geometry}
              material={materials["Material.007"]}
              position={[-0.216, -0.646, -0.385]}
              scale={0.258}
            />
            <mesh
              geometry={nodes.Plane001_Material002_0.geometry}
              material={materials["Material.002"]}
              position={[-0.216, -0.646, -0.385]}
              scale={0.258}
            />
            <mesh
              geometry={nodes.Sphere004_Material008_0.geometry}
              material={materials["Material.008"]}
              position={[-0.216, -0.646, -0.385]}
              scale={0.258}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/arcanum_2/scene.gltf");

